//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Pipeline.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace AnFake.Api.Pipeline.Antlr {
using System;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public partial class PipelineLexer : Lexer {
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, Identifier=8, 
		QuotedIdentifier=9, Spaces=10;
	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "Identifier", 
		"QuotedIdentifier", "Spaces"
	};


	public PipelineLexer(ICharStream input)
		: base(input)
	{
		Interpreter = new LexerATNSimulator(this,_ATN);
	}

	private static readonly string[] _LiteralNames = {
		null, "'=>'", "'->'", "'('", "')'", "'['", "']'", "'as'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, "Identifier", "QuotedIdentifier", 
		"Spaces"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Pipeline.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public static readonly string _serializedATN =
		"\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x2\f>\b\x1\x4\x2\t"+
		"\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t"+
		"\t\t\x4\n\t\n\x4\v\t\v\x3\x2\x3\x2\x3\x2\x3\x3\x3\x3\x3\x3\x3\x4\x3\x4"+
		"\x3\x5\x3\x5\x3\x6\x3\x6\x3\a\x3\a\x3\b\x3\b\x3\b\x3\t\x3\t\a\t+\n\t\f"+
		"\t\xE\t.\v\t\x3\n\x3\n\x6\n\x32\n\n\r\n\xE\n\x33\x3\n\x3\n\x3\v\x6\v\x39"+
		"\n\v\r\v\xE\v:\x3\v\x3\v\x2\x2\f\x3\x3\x5\x4\a\x5\t\x6\v\a\r\b\xF\t\x11"+
		"\n\x13\v\x15\f\x3\x2\a\x5\x2\x43\\\x61\x61\x63|\x6\x2\x32;\x43\\\x61\x61"+
		"\x63|\x3\x2))\f\x2\"\"%%\'(--/<??\x41\\^^\x61\x61\x63|\x5\x2\v\f\xF\xF"+
		"\"\"@\x2\x3\x3\x2\x2\x2\x2\x5\x3\x2\x2\x2\x2\a\x3\x2\x2\x2\x2\t\x3\x2"+
		"\x2\x2\x2\v\x3\x2\x2\x2\x2\r\x3\x2\x2\x2\x2\xF\x3\x2\x2\x2\x2\x11\x3\x2"+
		"\x2\x2\x2\x13\x3\x2\x2\x2\x2\x15\x3\x2\x2\x2\x3\x17\x3\x2\x2\x2\x5\x1A"+
		"\x3\x2\x2\x2\a\x1D\x3\x2\x2\x2\t\x1F\x3\x2\x2\x2\v!\x3\x2\x2\x2\r#\x3"+
		"\x2\x2\x2\xF%\x3\x2\x2\x2\x11(\x3\x2\x2\x2\x13/\x3\x2\x2\x2\x15\x38\x3"+
		"\x2\x2\x2\x17\x18\a?\x2\x2\x18\x19\a@\x2\x2\x19\x4\x3\x2\x2\x2\x1A\x1B"+
		"\a/\x2\x2\x1B\x1C\a@\x2\x2\x1C\x6\x3\x2\x2\x2\x1D\x1E\a*\x2\x2\x1E\b\x3"+
		"\x2\x2\x2\x1F \a+\x2\x2 \n\x3\x2\x2\x2!\"\a]\x2\x2\"\f\x3\x2\x2\x2#$\a"+
		"_\x2\x2$\xE\x3\x2\x2\x2%&\a\x63\x2\x2&\'\au\x2\x2\'\x10\x3\x2\x2\x2(,"+
		"\t\x2\x2\x2)+\t\x3\x2\x2*)\x3\x2\x2\x2+.\x3\x2\x2\x2,*\x3\x2\x2\x2,-\x3"+
		"\x2\x2\x2-\x12\x3\x2\x2\x2.,\x3\x2\x2\x2/\x31\t\x4\x2\x2\x30\x32\t\x5"+
		"\x2\x2\x31\x30\x3\x2\x2\x2\x32\x33\x3\x2\x2\x2\x33\x31\x3\x2\x2\x2\x33"+
		"\x34\x3\x2\x2\x2\x34\x35\x3\x2\x2\x2\x35\x36\t\x4\x2\x2\x36\x14\x3\x2"+
		"\x2\x2\x37\x39\t\x6\x2\x2\x38\x37\x3\x2\x2\x2\x39:\x3\x2\x2\x2:\x38\x3"+
		"\x2\x2\x2:;\x3\x2\x2\x2;<\x3\x2\x2\x2<=\b\v\x2\x2=\x16\x3\x2\x2\x2\x6"+
		"\x2,\x33:\x3\b\x2\x2";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
} // namespace AnFake.Api.Pipeline.Antlr
